### ISSUE TITLE
请问一台服务器上能同时运行两个agentd么

### ISSUE THREAD

**Issue by kys1230** [cenalulu/mysql-mmm#4]
我有三台服务器 每台服务器上面有两个隔离的mysql实例
我想搭建两套mysql-mmm 请问可以实现么

**Comment by cenalulu** [comment]
可以，agentd在配置文件里有自己的端口。同一台机器上启动两个mmm-agentd实例在不同端口，用不同的实例名字就行

**Comment by kys1230** [comment]
@cenalulu 我看了配置文件 并没有看到有配置端口的地方 。 请问是在mmm_agent.conf 中还是在mmm_common.conf 中额。。 官方有相关的配置文章么？

**Comment by cenalulu** [comment]
@kys1230 具体见http://mysql-mmm.org/mysql-mmm.html#SEC55 ， 不是所有配置都在conf里默认有的，所有支持的配置项还是要查wiki

**Comment by kys1230** [comment]
我应该如何通过命令行来指定配置文件启动agentd与monitor呢?

**Comment by kys1230** [comment]
能帮忙写个大概的例子么    试了很久 好像配的都不对.. 
我是需要在写另外一份的配置文件吧 , 下面是配置文件
[root@master mysql-mmm]# cat mmm_agent2.conf mmm_common_2.conf 
include mmm_common_2.conf
this db4
active_master_role      writer

host default>
    cluster_interface       eth1
    pid_path                /var/run/mysql-mmm/mmm_agentd_2.pid
    bin_path                /usr/libexec/mysql-mmm/
    replication_user        kyo
    replication_password    123
    agent_user              mmm_agent
    agent_password          123456
/host>
host db4>
    ip      192.168.5.203
    mysql_port 3316
    mode    master
    peer    db5
/host>
host db5>
    ip      192.168.5.168
    mode    master
    peer    db4
/host>
role writer>
    hosts   db4, db5
    ips     192.168.5.172
    mode    exclusive
/role>
role reader>
    hosts   db4, db5
    ips     192.168.5.173
    mode    balanced
/role>
所有少的<括号 都是有的
